CRITICAL - 2022-03-15 08:17:08 --> Class 'App\Controllers\mysqli' not found
#0 C:\xampp\htdocs\almexterno\app\Controllers\Usuario.php(148): App\Controllers\Usuario->_exportarTablas('localhost', 'root', '', 'almexterno')
#1 C:\xampp\htdocs\almexterno\system\CodeIgniter.php(948): App\Controllers\Usuario->generarBackup()
#2 C:\xampp\htdocs\almexterno\system\CodeIgniter.php(444): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\xampp\htdocs\almexterno\system\CodeIgniter.php(344): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\almexterno\index.php(36): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-03-15 09:16:22 --> unlink(public/respaldo_2022-03-15_62309cc053cd5.sql): No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'unlink(public/r...', 'C:\\xampp\\htdocs...', 157, Array)
#1 C:\xampp\htdocs\almexterno\app\Controllers\Usuario.php(157): unlink('public/respaldo...')
#2 C:\xampp\htdocs\almexterno\system\CodeIgniter.php(948): App\Controllers\Usuario->eliminarBackup('respaldo_2022-0...')
#3 C:\xampp\htdocs\almexterno\system\CodeIgniter.php(444): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\almexterno\system\CodeIgniter.php(344): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\almexterno\index.php(36): CodeIgniter\CodeIgniter->run()
#6 {main}
