ERROR - 2022-05-10 13:23:49 --> Error connecting to the database: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

CRITICAL - 2022-05-10 13:23:49 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

#0 C:\xampp\htdocs\almexterno\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\almexterno\app\Models\UsuarioModel.php(11): CodeIgniter\Database\BaseConnection->query('select * from u...')
#2 C:\xampp\htdocs\almexterno\app\Controllers\Inicio.php(38): App\Models\UsuarioModel->validaUsuario('LCALDERONS')
#3 C:\xampp\htdocs\almexterno\system\CodeIgniter.php(948): App\Controllers\Inicio->index()
#4 C:\xampp\htdocs\almexterno\system\CodeIgniter.php(444): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Inicio))
#5 C:\xampp\htdocs\almexterno\system\CodeIgniter.php(344): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\almexterno\index.php(36): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-10 13:23:49 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Malformed UTF-8 characters, possibly incorrectly encoded". in C:\xampp\htdocs\almexterno\system\Format\JSONFormatter.php:42
Stack trace:
#0 C:\xampp\htdocs\almexterno\system\Format\JSONFormatter.php(42): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Malformed UTF-8...')
#1 C:\xampp\htdocs\almexterno\system\API\ResponseTrait.php(407): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\almexterno\system\API\ResponseTrait.php(114): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\almexterno\system\Debug\Exceptions.php(141): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
